project:
  type: website
  output-dir: docs

website:
  title: "GEOG70812: Local Scale Mitigation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - results.qmd
      - shading.qmd
      - area.qmd
      - temperature.qmd
      - quiz.qmd
      - more.qmd
